#!/usr/bin/env bash

#create vpc
VPC_ID=$(aws ec2 create-vpc \
    --cidr-block "172.1.0.0/16" \
    --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=MyNewVPC}]' \
    --region ap-south-1 \
    --query Vpc.VpcId \
    --output text)

echo $VPC_ID

#Turn on DNS host names
aws ec2 modify-vpc-attribute \
    --vpc-id $VPC_ID \
    --region ap-south-1 \
    --enable-dns-hostnames "{\"Value\":true}"

# create IGW
IGW_ID=$(aws ec2 create-internet-gateway \
    --region ap-south-1 \
    --query 'InternetGateway.InternetGatewayId' \
    --output text)

echo $IGW_ID

#attach IGW
aws ec2 attach-internet-gateway \
    --internet-gateway-id $IGW_ID \
    --vpc-id $VPC_ID \
    --region ap-south-1

#get route table
ROUTE_TABLE_ID=$(aws ec2 describe-route-tables \
    --filters Name=vpc-id,Values=$VPC_ID \
    --query RouteTables[0].RouteTableId \
    --region ap-south-1 \
    --output text)

echo $ROUTE_TABLE_ID

#create subnet
SUBNET_ID=$(aws ec2 create-subnet \
    --vpc-id $VPC_ID \
    --cidr-block 172.1.0.0/20 \
    --tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=my-ipv6-only-subnet}]' \
    --region ap-south-1 \
    --query Subnet.SubnetId \
    --output text)

echo $SUBNET_ID

aws ec2 modify-subnet-attribute \
    --subnet-id $SUBNET_ID \
    --region ap-south-1 \
    --map-public-ip-on-launch

#associate route table to subnet
aws ec2 associate-route-table --route-table-id $ROUTE_TABLE_ID --subnet-id $SUBNET_ID --region ap-south-1

#add route 
aws ec2 create-route \
    --region ap-south-1 \
    --route-table-id $ROUTE_TABLE_ID \
    --destination-cidr-block 0.0.0.0/0 \
    --gateway-id $IGW_ID